services:
  - docker
  - mysql
  - postgresql
  - mongodb
  - redis
  - memcached

env:
  global:
    - KERL_DEFAULT_INSTALL_DIR="$HOME/.kerl"

addons:
  apt:
    packages:
      - libsnappy-dev
  homebrew:
    update: false
    taps: mongodb/brew
    packages:
      - kerl
      - snappy
      - openssl@1.1
      - mysql
      - postgresql
      - redis
      - memcached
      - mongodb-community

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then kerl update releases ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then kerl list builds | grep ${OTP_VERSION} || travis_wait 45 kerl build ${OTP_VERSION} ${OTP_VERSION} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then kerl list installations | grep ${OTP_VERSION} || kerl install ${OTP_VERSION} ; fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ulimit -n 2048 # by default travis osx has "ulimit -n 256"
      brew services start redis
      brew services start memcached
      brew services start mysql
      brew services start mongodb-community
      export PG_DATA=$(brew --prefix)/var/postgres
      rm -rf $PG_DATA
      initdb $PG_DATA -E utf8
      pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
      createuser -s postgres
    fi

sudo: required
dist: trusty
language: erlang
jobs:
  include:
    - os: linux
      otp_release: 22.0
      env: OTP_VERSION=22.0
    - os: linux
      otp_release: 22.2
      env: OTP_VERSION=22.2
    - os: linux
      otp_release: 22.3
      env: OTP_VERSION=22.3
    - os: linux
      otp_release: 23.0
      env: OTP_VERSION=23.0
    - os: osx
      language: generic
      osx_image: xcode11.3
      env: OTP_VERSION=22.3

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /var/cache/apt
    - plts
    - plts_base
    - $HOME/.cache/rebar3
    - $HOME/.kerl
    - $HOME/.kerlrc

before_script:
  - if [ $TRAVIS_OS_NAME == osx ] ; then  . ${KERL_DEFAULT_INSTALL_DIR}/${OTP_VERSION}/activate ; fi
  - mysql -e "CREATE DATABASE vmq_test_database;" -uroot
  - mysql -e "CREATE USER 'vmq_test_user' IDENTIFIED BY 'vmq_test_password';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'vmq_test_user';" -uroot
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql -u root -e "use mysql; update user set plugin='mysql_native_password' where user='vmq_test_user'; flush privileges"; fi
  - psql -c "CREATE DATABASE vmq_test_database;" -U postgres
  - psql -c "CREATE USER vmq_test_user WITH PASSWORD 'vmq_test_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE vmq_test_database to vmq_test_user;" -U postgres
  - epmd -daemon

script:
  - ./rebar3 as all_tests do dialyzer, eunit, ct
