services:
  - docker
  - mysql
  - postgresql
  - mongodb
  - redis
  - memcached

env:
  global:
    - KERL_DEFAULT_INSTALL_DIR="$HOME/.kerl"

addons:
  apt:
    packages:
      - libsnappy-dev
  homebrew:
    update: true
    packages:
      - kerl
      - snappy
      - openssl@1.1
      - mysql
      - postgres
      - redis
      - memcached


before_install:
  # MySQL
  - if [ "$TRAVIS_OS_NAME" == osx ] ; then brew services start mysql; fi
  - mysql -e "CREATE DATABASE vmq_test_database;" -uroot
  - mysql -e "CREATE USER 'vmq_test_user' IDENTIFIED BY 'vmq_test_password';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'vmq_test_user';" -uroot
  # PostgreSQL
  - if [ $TRAVIS_OS_NAME == osx ] ; then rm -rf /usr/local/var/postgres ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then initdb /usr/local/var/postgres ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then pg_ctl -D /usr/local/var/postgres start && sleep 3 || true ; fi
  - psql -c "CREATE DATABASE vmq_test_database;" -U postgres
  - psql -c "CREATE USER vmq_test_user WITH PASSWORD 'vmq_test_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE vmq_test_database to vmq_test_user;" -U postgres
  # Redis
  - if [ "$TRAVIS_OS_NAME" == osx ] ; then brew services start redis; fi
  # Memcached
  - if [ "$TRAVIS_OS_NAME" == osx ] ; then brew services start memcached; fi

install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then kerl update releases ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then kerl list builds | grep ${OTP_VERSION} || travis_wait 45 kerl build ${OTP_VERSION} ${OTP_VERSION} ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then kerl list installations | grep ${OTP_VERSION} || kerl install ${OTP_VERSION} ; fi

sudo: required
dist: trusty
language: erlang
jobs:
  include:
    - os: linux
      otp_release: 22.0
      env: OTP_VERSION=22.0
    - os: linux
      otp_release: 22.2
      env: OTP_VERSION=22.2
    - os: linux
      otp_release: 22.3
      env: OTP_VERSION=22.3
    - os: linux
      otp_release: 23.0
      env: OTP_VERSION=23.0
    - os: osx
      language: generic
      osx_image: xcode11.3
      env: OTP_VERSION=22.3
cache:
  brew: true
  directories:
    - plts
    - plts_base
    - $HOME/.cache/rebar3
    - /var/cache/apt
    - $HOME/.kerl
    - $HOME/.kerlrc

before_script:
  - if [ $TRAVIS_OS_NAME == osx ] ; then  . ${KERL_DEFAULT_INSTALL_DIR}/${OTP_VERSION}/activate ; fi
  - epmd -daemon

script:
  - ./rebar3 as all_tests do dialyzer, eunit, ct
