otp_release:
    - 18.3
    - 19.3
    - 20.0

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: false

services:
    - mysql
    - postgresql
    - mongodb
    - redis
    - memcached 

before_install:
    - ./travis_fetch_otp.sh
    - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew update
        brew install wget
        brew outdated openssl || brew upgrade openssl || brew link openssl
        brew outdated cmake || brew upgrade cmake
      fi
    - mysql -e "CREATE DATABASE vmq_test_database;" -uroot
    - mysql -e "CREATE USER 'vmq_test_user' IDENTIFIED BY 'vmq_test_password';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'vmq_test_user';" -uroot
    - psql -c "CREATE DATABASE vmq_test_database;" -U postgres
    - psql -c "CREATE USER vmq_test_user WITH PASSWORD 'vmq_test_password';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE vmq_test_database to vmq_test_user;" -U postgres

before_script: "epmd -daemon"
script: "./rebar3 as all_tests do eunit, ct"
